### ISSUE TITLE
Make ctrl command shift w shortcut configurable

### ISSUE THREAD

**Issue by ogomez92** [chigkim/VOCR#10]
Hello,
Is it possible to make the shortcut configurable?
Steam doesn't like this shortcut and it takes precedence over VOCR, so basically I cannot use Steam at all.

Thanks.

**Comment by chigkim** [comment]
The shortcuts are not configurable yet.

In the mean time, you can quit VOCR from the menu extra when you need 
the shortcuts.

**Comment by ogomez92** [comment]
Even better, I changed the shortcut myself in Xcode, built for Aple
Silicon and notarized the ap.

**Comment by chigkim** [comment]
Great, I saw a significant speed increase when using VOCR with M1, so 
enjoy it!

**Comment by jprykiel** [comment]
Hello,
I would plus one this request to. I have 2 reasons for wishing to change this shortcut.
1, if you want to explore the scan result, you have to switch hands on the modifier keys in order to use the Arrow keys.
2, w is in a different place on non-English keyboards, and I would suggest to use a letter that would be under your right hand, and that would be in the same location on as many keyboards as possible.
My suggestion would be l as in look.
Cheers,
JPR

**Comment by mrgrieves4** [comment]
I'd like to add a vote for this too, as I'm finding that I don't quite have the coordination to pull off this move that easily.

In an ideal world, I'd like to be able to assign it in keyboard commander or numpad commander so I can cut down on the number of keys to press at once.  I'm guessing this would need a separate app to be able to run it from there, so might not be feasible but thought I'd mention it.

**Comment by chigkim** [comment]
done!
https://github.com/chigkim/VOCR/releases/tag/v2.0.0-alpha.10
